

spring:
 cache:
  type: None
salesforce:
  client:
    clientId: 3MVG9pRzvMkjMb6k3uwP6.2qCzcRRGmjJGyFFktSzJ0vWZivEqTQZsPBOeV3nKDHCOsppGiG_.fPGhExKOAKO
    clientSecret:  440F672D9469A1F0F3B76D0F479A80CCB4E57E9A15283D4F5D6266CC55886B56
    accessTokenUri: https://login.salesforce.com/services/oauth2/token
    userAuthorizationUri: https://login.salesforce.com/services/oauth2/authorize
    tokenName: oauth_token
    authenticationScheme: header
    clientAuthenticationScheme: form
    grant-type: authorization_code
  resource:
    userInfoUri: https://login.salesforce.com/services/oauth2/userinfo

salesforce1:
  client:
    clientId: 3MVG9pRzvMkjMb6k3uwP6.2qCzcRRGmjJGyFFktSzJ0vWZivEqTQZsPBOeV3nKDHCOsppGiG_.fPGhExKOAKO
    clientSecret: 440F672D9469A1F0F3B76D0F479A80CCB4E57E9A15283D4F5D6266CC55886B56
    accessTokenUri: https://test.salesforce.com/services/oauth2/token
    userAuthorizationUri: https://test.salesforce.com/services/oauth2/authorize
    tokenName: oauth_token
    authenticationScheme: header
    clientAuthenticationScheme: form
    grant-type: authorization_code
  resource:
    userInfoUri: https://test.salesforce.com/services/oauth2/userinfo


